create table TBL_T_AGENCY (AGENCY_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		AGENCY_COMPANY_ID varchar(32) not null comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (AGENCY_ID),
		unique (AGENCY_COMPANY_ID)) comment='代理店' ENGINE=InnoDB;
create table TBL_T_CALL_LOG (CALL_LOG_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		CALL_LOG_NO bigint not null comment '企業ごとの一連番号 （登録時に最大値＋1を設定）',
		STATUS varchar(2) not null comment '0：通話中でない　1：通話中',
		START_DATE datetime(3) not null comment '',
		END_DATE datetime(3) not null comment '開始時は開始日時と同じ値を設定',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		DELETE_DATE datetime(3) comment '',
		primary key (CALL_LOG_ID),
		unique (COMPANY_ID,
		CALL_LOG_NO)) comment='通話ログ' ENGINE=InnoDB;
create table TBL_T_CALL_LOG_DETAIL (CALL_LOG_DETAIL_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		CALL_LOG_ID bigint not null comment '',
		LOG longtext not null comment 'LONGTEXT 使用',
		BEGIN integer comment 'ミリ秒',
		END integer comment 'ミリ秒',
		VOICE_EXISTENCE bit not null comment 'false：無、true：有',
		BORDER bit not null comment 'false：区切行でない、true：区切行',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		DELETE_DATE datetime(3) comment '',
		primary key (CALL_LOG_DETAIL_ID)) comment='通話ログ詳細' ENGINE=InnoDB;
create table TBL_T_CALL_USER (CALL_USER_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		CALL_LOG_ID bigint not null comment '',
		USER_ID varchar(32) not null comment '通話していた担当者',
		USER_NAME varchar(100) not null comment '',
		START_DATE datetime(3) not null comment '',
		END_DATE datetime(3) not null comment '開始時は開始日時と同じ値を設定',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		DELETE_DATE datetime(3) comment '',
		primary key (CALL_USER_ID)) comment='通話者ログ' ENGINE=InnoDB;
create table TBL_T_CHECKWORD (CHECKWORD_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		CHECKWORD varchar(100) not null comment '',
		COLOR_THEME varchar(20) not null comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (CHECKWORD_ID),
		unique (COMPANY_ID,
		CHECKWORD)) comment='チェックワード' ENGINE=InnoDB;
create table TBL_T_COMPANY_MANAGEMENT (COMPANY_MANAGEMENT_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		COMPANY_NAME varchar(100) comment '',
		AGENCY_COMPANY_ID varchar(32) not null comment '',
		RECAIUS_LICENSE_ID bigint not null comment '',
		RECAIUS_MODEL_ID integer not null comment '',
		ENERGY_THRESHOLD integer not null comment '0～1000',
		HASHED_COMPANY_ID varchar(100) comment '企業IDのSHA-256ハッシュ',
		SAVE_VOICE bit comment 'true:通話時に音声ファイルを保存する false:通話時に音声ファイルの保存をしない',
		PERMIT_IP_ADDRESS varchar(3000) comment 'TEXT型で定義する',
		VOICE_KEEP_DAYS integer comment '',
		LOGICAL_DELETE_LOG_KEEP_DAYS integer comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (COMPANY_MANAGEMENT_ID),
		unique (COMPANY_ID),
		unique (HASHED_COMPANY_ID)) comment='企業管理' ENGINE=InnoDB;
create table TBL_T_KNOWLEDGE (KNOWLEDGE_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		KNOWLEDGE_NO bigint not null comment '企業ごとの一連番号 （登録時に最大値＋1を設定）',
		TITLE varchar(100) not null comment '',
		CONTENT longtext not null comment 'LONGTEXT 使用',
		SCRIPT longtext comment 'LONGTEXT 使用',
		CLICK_COUNT bigint not null comment '登録時に 0 を設定',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (KNOWLEDGE_ID),
		unique (COMPANY_ID,
		TITLE),
		unique (COMPANY_ID,
		KNOWLEDGE_NO)) comment='ナレッジ DB' ENGINE=InnoDB;
create table TBL_T_KNOWLEDGE_TAG (KNOWLEDGE_TAG_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		KNOWLEDGE_ID bigint not null comment '',
		TAG_ID bigint not null comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		primary key (KNOWLEDGE_TAG_ID),
		unique (KNOWLEDGE_ID,
		TAG_ID)) comment='ナレッジ－タグ関連テーブル' ENGINE=InnoDB;
create table TBL_T_MANUAL (MANUAL_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		KNOWLEDGE_ID bigint not null comment '',
		MANUAL_NAME varchar(100) comment '',
		MANUAL_PAGE varchar(10) comment '',
		MANUAL_URL varchar(255) comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (MANUAL_ID)) comment='マニュアル' ENGINE=InnoDB;
create table TBL_T_RECAIUS_LICENSE (RECAIUS_LICENSE_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		SERVICE_ID varchar(300) not null comment '',
		PASSWORD varchar(300) not null comment '',
		AGENCY_COMPANY_ID varchar(32) comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (RECAIUS_LICENSE_ID),
		unique (SERVICE_ID)) comment='リカイアスライセンス' ENGINE=InnoDB;
create table TBL_T_REFERENCE (REFERENCE_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		KNOWLEDGE_ID bigint not null comment '',
		REFERENCE_URL varchar(255) comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (REFERENCE_ID)) comment='参照先' ENGINE=InnoDB;
create table TBL_T_TAG (TAG_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		TAG_NAME varchar(100) not null comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (TAG_ID),
		unique (COMPANY_ID,
		TAG_NAME)) comment='タグ' ENGINE=InnoDB;
create table TBL_T_USE_TIME (USE_TIME_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		COMPANY_NAME varchar(100) comment '（トライアルでは使用しない）',
		USER_ID varchar(32) not null comment '',
		USER_NAME varchar(100) not null comment '',
		TYPE varchar(2) not null comment '1：音声解析　2：要約',
		START_DATE datetime(3) not null comment '',
		END_DATE datetime(3) not null comment '開始時は開始日時と同じ値を設定',
		USE_TIME bigint not null comment '単位：ミリ秒／登録時に 0 を設定',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (USE_TIME_ID)) comment='利用時間' ENGINE=InnoDB;
create table TBL_T_VOICE_ENCODE_QUEUE (VOICE_ENCODE_QUEUEL_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		CALL_LOG_ID bigint not null comment '',
		CALL_LOG_DETAIL_ID bigint not null comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		primary key (VOICE_ENCODE_QUEUEL_ID)) comment='通話音声圧縮キュー' ENGINE=InnoDB;
create index IDX_CALLLOG_COMPANY on TBL_T_CALL_LOG (COMPANY_ID);
create index IDX_CALLLOGDTL_COMPANY on TBL_T_CALL_LOG_DETAIL (COMPANY_ID);
create index IDX_CALLUSER_COMPANY on TBL_T_CALL_USER (COMPANY_ID);
create index IDX_CALLUSER_START_DATE on TBL_T_CALL_USER (START_DATE);
create index IDX_CALLUSER_CALLLOG on TBL_T_CALL_USER (CALL_LOG_ID);
create index IDX_CHECKWORD_COMPANY on TBL_T_CHECKWORD (COMPANY_ID);
create index IDX_COMPANY_MANAGEMENT on TBL_T_COMPANY_MANAGEMENT (COMPANY_ID);
create index IDX_KNOWLEDGE_COMPANY on TBL_T_KNOWLEDGE (COMPANY_ID);
create index IDX_KNOWLEDGE_TAG_KNOWLEDGE on TBL_T_KNOWLEDGE_TAG (KNOWLEDGE_ID);
create index IDX_KNOWLEDGE_TAG_TAG on TBL_T_KNOWLEDGE_TAG (TAG_ID);
create index IDX_MANUAL_COMPANY on TBL_T_MANUAL (COMPANY_ID);
create index IDX_MANUAL_KNOWLEDGE on TBL_T_MANUAL (KNOWLEDGE_ID);
create index IDX_REFERENCE_COMPANY on TBL_T_REFERENCE (COMPANY_ID);
create index IDX_REFERENCE_KNOWLEDGE on TBL_T_REFERENCE (KNOWLEDGE_ID);
create index IDX_TAG_COMPANY on TBL_T_TAG (COMPANY_ID);
create index IDX_USETIME_START_DATE on TBL_T_USE_TIME (START_DATE);
create index IDX_USETIME_END_DATE on TBL_T_USE_TIME (END_DATE);
create index IDX_USETIME_COMPANY on TBL_T_USE_TIME (COMPANY_ID);
create index IDX_CALLLOGDTL_COMPANY on TBL_T_VOICE_ENCODE_QUEUE (COMPANY_ID);
