/**
 * Copyright (C) 2017 OPTiM Corp. All Rights Reserved
 * システム名：
 * ソースファイル名：KnowledgeTag.java
 */

package cloud.optim.callcentersolution.api.entity;
// Generated by Hibernate Tools 3.2.2.CR1


import java.util.Date;

/**
 * ナレッジ／タグ間の関連テーブル
 */
public class KnowledgeTag  implements java.io.Serializable {


	/**
	 * ナレッジ－タグ関連 ID
	 */
	private Long knowledgeTagId;

	/**
	 * 更新日時
	 */
	private Date updateDate;

	/**
	 * ナレッジ ID
	 */
	private Long knowledgeId;

	/**
	 * タグ ID
	 */
	private Long tagId;

	/**
	 * 作成日時
	 */
	private Date createDate;

	/**
	 * 作成ユーザ ID
	 */
	private String createUserId;

	/**
	 * 作成ユーザ名
	 */
	private String createUserName;


	/**
	 * KnowledgeTag デフォルトコンストラクター
	 */
	public KnowledgeTag() {
	}

	/**
	 * KnowledgeTag フルコンストラクター
	 * @param knowledgeId ナレッジ ID
	 * @param tagId タグ ID
	 * @param createDate 作成日時
	 * @param createUserId 作成ユーザ ID
	 * @param createUserName 作成ユーザ名
	 */
	public KnowledgeTag(Long knowledgeId, Long tagId, Date createDate, String createUserId, String createUserName) {
		this.knowledgeId = knowledgeId;
		this.tagId = tagId;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.createUserName = createUserName;
	}

	// * ナレッジ－タグ関連 ID */
	/**
	 * @return knowledgeTagId (ナレッジ－タグ関連 ID)
	 */
	public Long getKnowledgeTagId() {
		return this.knowledgeTagId;
	}

	/**
	 * @param knowledgeTagId ナレッジ－タグ関連 ID
	 */
	public void setKnowledgeTagId(Long knowledgeTagId) {
		this.knowledgeTagId = knowledgeTagId;
	}

	// * 更新日時 */
	/**
	 * @return updateDate (更新日時)
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * @param updateDate 更新日時
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	// * ナレッジ ID */
	/**
	 * @return knowledgeId (ナレッジ ID)
	 */
	public Long getKnowledgeId() {
		return this.knowledgeId;
	}

	/**
	 * @param knowledgeId ナレッジ ID
	 */
	public void setKnowledgeId(Long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	// * タグ ID */
	/**
	 * @return tagId (タグ ID)
	 */
	public Long getTagId() {
		return this.tagId;
	}

	/**
	 * @param tagId タグ ID
	 */
	public void setTagId(Long tagId) {
		this.tagId = tagId;
	}

	// * 作成日時 */
	/**
	 * @return createDate (作成日時)
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * @param createDate 作成日時
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	// * 作成ユーザ ID */
	/**
	 * @return createUserId (作成ユーザ ID)
	 */
	public String getCreateUserId() {
		return this.createUserId;
	}

	/**
	 * @param createUserId 作成ユーザ ID
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	// * 作成ユーザ名 */
	/**
	 * @return createUserName (作成ユーザ名)
	 */
	public String getCreateUserName() {
		return this.createUserName;
	}

	/**
	 * @param createUserName 作成ユーザ名
	 */
	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}


	/**
	 * toString
	 * @return String
	*/
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("knowledgeTagId").append("='").append(getKnowledgeTagId()).append("' ");
		buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");
		buffer.append("knowledgeId").append("='").append(getKnowledgeId()).append("' ");
		buffer.append("tagId").append("='").append(getTagId()).append("' ");
		buffer.append("createDate").append("='").append(getCreateDate()).append("' ");
		buffer.append("createUserId").append("='").append(getCreateUserId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	@Override
	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof KnowledgeTag) ) return false;
		KnowledgeTag castOther = ( KnowledgeTag ) other;

		return ( (this.getKnowledgeTagId()==castOther.getKnowledgeTagId()) || ( this.getKnowledgeTagId()!=null && castOther.getKnowledgeTagId()!=null && this.getKnowledgeTagId().equals(castOther.getKnowledgeTagId()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getKnowledgeId()==castOther.getKnowledgeId()) || ( this.getKnowledgeId()!=null && castOther.getKnowledgeId()!=null && this.getKnowledgeId().equals(castOther.getKnowledgeId()) ) )
 && ( (this.getTagId()==castOther.getTagId()) || ( this.getTagId()!=null && castOther.getTagId()!=null && this.getTagId().equals(castOther.getTagId()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUserId()==castOther.getCreateUserId()) || ( this.getCreateUserId()!=null && castOther.getCreateUserId()!=null && this.getCreateUserId().equals(castOther.getCreateUserId()) ) )
 && ( (this.getCreateUserName()==castOther.getCreateUserName()) || ( this.getCreateUserName()!=null && castOther.getCreateUserName()!=null && this.getCreateUserName().equals(castOther.getCreateUserName()) ) );
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + ( getKnowledgeTagId() == null ? 0 : this.getKnowledgeTagId().hashCode() );
		result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
		result = 37 * result + ( getKnowledgeId() == null ? 0 : this.getKnowledgeId().hashCode() );
		result = 37 * result + ( getTagId() == null ? 0 : this.getTagId().hashCode() );
		result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
		result = 37 * result + ( getCreateUserId() == null ? 0 : this.getCreateUserId().hashCode() );
		result = 37 * result + ( getCreateUserName() == null ? 0 : this.getCreateUserName().hashCode() );
		return result;
	}

  // The following is extra code specified in the hbm.xml files

	/** serialVersionUID  */
	private static final long serialVersionUID = 1L;
		
  // end of extra code specified in the hbm.xml files

}


